function jakubian = vk(tht1,tht2,tht3)
%VK Generated using vkGeneration.m
%    JAKUBIAN = VK(THT1,THT2,THT3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Apr-2025 13:20:07

t2 = cos(tht1);
t3 = sin(tht1);
t4 = pi./2.0;
t5 = -t4;
t7 = t4+tht3-7.146907175572792e-2;
t6 = t5+tht2+7.146907175572792e-2;
t9 = cos(t7);
t11 = sin(t7);
t8 = cos(t6);
t10 = sin(t6);
t12 = (t8.*t9)./4.0;
t13 = (t10.*t11)./4.0;
t15 = (t2.*t8.*t11)./4.0;
t16 = (t2.*t9.*t10)./4.0;
t17 = (t3.*t8.*t11)./4.0;
t18 = (t3.*t9.*t10)./4.0;
t14 = -t13;
t19 = -t15;
t20 = -t16;
mt1 = [t2./5.0e+1-t3.*t8.*2.380677458203862e-1+t3.*t13-(t3.*t8.*t9)./4.0,t3.*(-1.0./5.0e+1)-t2.*t8.*2.380677458203862e-1+t2.*t13-(t2.*t8.*t9)./4.0,0.0,t19+t20-t2.*t10.*2.380677458203862e-1,t17+t18+t3.*t10.*2.380677458203862e-1];
mt2 = [t8.*2.380677458203862e-1+t12+t14,t19+t20,t17+t18,t12+t14];
jakubian = reshape([mt1,mt2],3,3);
